In [50]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [51]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ML_Projects/Customer_Churn_Prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [52]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [53]:
df.drop("customerID", axis=1, inplace=True)

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [55]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [56]:
df["Churn"] = df["Churn"].map({"No": 0,"Yes": 1})

In [57]:
df.isna().sum().sum()

np.int64(11)

In [58]:
df.dropna(inplace=True)

In [59]:
x = df.drop("Churn", axis=1)
y = df["Churn"]

In [60]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [61]:
categorical_features = [col for col in x.columns if x[col].dtype == "O"]
categorical_features

['gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod']

In [62]:
numerical_features = [col for col in x.columns if x[col].dtype != "O"]
numerical_features

['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

In [63]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
numerical_transformer=StandardScaler()
categorical_transformer=OneHotEncoder(handle_unknown="ignore")


preprocessor=ColumnTransformer(
    [
        ("OneHotEncoder",categorical_transformer,categorical_features),
        ("StandardScaler",numerical_transformer,numerical_features)
    ]
)

In [64]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['gender', 'Partner', 'Dependents',
                                  'PhoneService', 'MultipleLines',
                                  'InternetService', 'OnlineSecurity',
                                  'OnlineBackup', 'DeviceProtection',
                                  'TechSupport', 'StreamingTV',
                                  'StreamingMovies', 'Contract',
                                  'PaperlessBilling', 'PaymentMethod']),
                                ('StandardScaler', StandardScaler(),
                                 ['SeniorCitizen', 'tenure', 'MonthlyCharges',
                                  'TotalCharges'])])

In [65]:
x_train=preprocessor.fit_transform(x_train)
x_test=preprocessor.transform(x_test)

In [66]:
x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50

In [67]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import recall_score,accuracy_score,precision_score,f1_score,roc_auc_score

In [68]:
# For decision tree
dt_params = {
    "criterion": "gini",
    "max_depth": 5,
    "min_samples_split": 10,
    "min_samples_leaf": 4,
    "class_weight": "balanced"
}

In [69]:
# For random forest
rf_params = {
    "n_estimators": 200,
    "max_depth": 10,
    "min_samples_split": 5,
    "min_samples_leaf": 2,
    "max_features": "sqrt",
    "class_weight": "balanced",
    "random_state": 42
}

In [70]:
models={
    "Logistic Regression":LogisticRegression(),
    "Decision Tree":DecisionTreeClassifier(**dt_params),
    "Random Forest":RandomForestClassifier(**rf_params)
}

for i in range(len(list(models))):
  model=list(models.values())[i]
  model.fit(x_train,y_train)

  y_train_pred=model.predict(x_train)
  y_test_pred=model.predict(x_test)

  print(model)
  print("Training Accuracy")
  print("Accuracy :", accuracy_score(y_train,y_train_pred))
  print("Precision:", precision_score(y_train,y_train_pred))
  print("Recall   :", recall_score(y_train,y_train_pred))
  print("F1 Score :", f1_score(y_train,y_train_pred))
  print("ROC-AUC  :", roc_auc_score(y_train,y_train_pred))
  print("\n")

  print("Testing Accuracy")
  print("Accuracy :", accuracy_score(y_test,y_test_pred))
  print("Precision:", precision_score(y_test,y_test_pred))
  print("Recall   :", recall_score(y_test,y_test_pred))
  print("F1 Score :", f1_score(y_test,y_test_pred))
  print("ROC-AUC  :", roc_auc_score(y_test,y_test_pred))
  print("-"*20,"\n")

LogisticRegression()
Training Accuracy
Accuracy : 0.8088888888888889
Precision: 0.6656151419558359
Recall   : 0.5645484949832776
F1 Score : 0.6109301483894318
ROC-AUC  : 0.7309425283633096


Testing Accuracy
Accuracy : 0.7874911158493249
Precision: 0.6205787781350482
Recall   : 0.516042780748663
F1 Score : 0.5635036496350365
ROC-AUC  : 0.7009061919232185
--------------------

DecisionTreeClassifier(class_weight='balanced', max_depth=5, min_samples_leaf=4,
                       min_samples_split=10)
Training Accuracy
Accuracy : 0.7751111111111111
Precision: 0.5538894095595126
Recall   : 0.7906354515050167
F1 Score : 0.6514191237255442
ROC-AUC  : 0.7800634884643727


Testing Accuracy
Accuracy : 0.7412935323383084
Precision: 0.5092250922509225
Recall   : 0.7379679144385026
F1 Score : 0.6026200873362445
ROC-AUC  : 0.7402327471514875
--------------------

RandomForestClassifier(class_weight='balanced', max_depth=10,
                       min_samples_leaf=2, min_samples_split=5,
                       n_estimators=200, random_state=42)
Training Accuracy
Accuracy : 0.8487111111111111
Precision: 0.6601990049751244
Recall   : 0.8876254180602007
F1 Score : 0.7572039942938659
ROC-AUC  : 0.8611250576983812


Testing Accuracy
Accuracy : 0.7547974413646056
Precision: 0.5288270377733598
Recall   : 0.7112299465240641
F1 Score : 0.6066134549600912
ROC-AUC  : 0.7409005492542876
--------------------

## Random forest has highest F!, recall. So we will fine tune it.

In [71]:
from sklearn.model_selection import GridSearchCV

In [72]:
params = {
    "n_estimators": [100, 200],
    "max_depth": [5, 10],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2],
    "max_features": ["sqrt"],
    "class_weight": ["balanced"]
}

In [73]:
grid = GridSearchCV(
    estimator=RandomForestClassifier(**rf_params),
    param_grid=params,
    scoring="recall",
    cv=5,
    verbose=2,
    n_jobs=-1
)

In [74]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              max_depth=10, min_samples_leaf=2,
                                              min_samples_split=5,
                                              n_estimators=200,
                                              random_state=42),
             n_jobs=-1,
             param_grid={'class_weight': ['balanced'], 'max_depth': [5, 10],
                         'max_features': ['sqrt'], 'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [100, 200]},
             scoring='recall', verbose=2)

In [75]:
print("Best Parameters:")
print(grid.best_params_)

Best Parameters:
{'class_weight': 'balanced', 'max_depth': 5, 'max_features': 'sqrt', 'min_samples_leaf': 2, 'min_samples_split': 2, 'n_estimators': 100}

In [76]:
best_model = grid.best_estimator_

In [77]:
y_train_pred = best_model.predict(x_train)
y_test_pred = best_model.predict(x_test)

In [78]:
print("Training Metrics")
print("Accuracy :", accuracy_score(y_train, y_train_pred))
print("Precision:", precision_score(y_train, y_train_pred))
print("Recall   :", recall_score(y_train, y_train_pred))
print("F1 Score :", f1_score(y_train, y_train_pred))
print("ROC-AUC  :", roc_auc_score(y_train, y_train_pred))
print("\n")

print("Testing Metrics")
print("Accuracy :", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred))
print("Recall   :", recall_score(y_test, y_test_pred))
print("F1 Score :", f1_score(y_test, y_test_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_test_pred))

Training Metrics
Accuracy : 0.7589333333333333
Precision: 0.5302568567696996
Recall   : 0.8147157190635451
F1 Score : 0.6424050632911392
ROC-AUC  : 0.7767283195801988


Testing Metrics
Accuracy : 0.7270788912579957
Precision: 0.4917763157894737
Recall   : 0.7994652406417112
F1 Score : 0.6089613034623218
ROC-AUC  : 0.7501682447158217

In [79]:
from sklearn.model_selection import RandomizedSearchCV

In [80]:
params = {
    "n_estimators": [100, 200, 300, 500],
    "max_depth": [5, 10, 15, 20, None],
    "min_samples_split": [2, 5, 10, 20],
    "min_samples_leaf": [1, 2, 4, 8],
    "max_features": ["sqrt", "log2"],
    "class_weight": [None, "balanced"]
}

In [81]:
random_search = RandomizedSearchCV(
    estimator=RandomForestClassifier(**rf_params),
    param_distributions=params,
    n_iter=25,
    scoring="recall",
    cv=5,
    verbose=2,
    random_state=42,
    n_jobs=-1
)

In [82]:
random_search.fit(x_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits

RandomizedSearchCV(cv=5,
                   estimator=RandomForestClassifier(class_weight='balanced',
                                                    max_depth=10,
                                                    min_samples_leaf=2,
                                                    min_samples_split=5,
                                                    n_estimators=200,
                                                    random_state=42),
                   n_iter=25, n_jobs=-1,
                   param_distributions={'class_weight': [None, 'balanced'],
                                        'max_depth': [5, 10, 15, 20, None],
                                        'max_features': ['sqrt', 'log2'],
                                        'min_samples_leaf': [1, 2, 4, 8],
                                        'min_samples_split': [2, 5, 10, 20],
                                        'n_estimators': [100, 200, 300, 500]},
                   random_state=42, scoring='recall', verbose=2)

In [83]:
best_model = random_search.best_estimator_

In [84]:
print("Best Parameters:")
print(random_search.best_params_)

Best Parameters:
{'n_estimators': 500, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'sqrt', 'max_depth': 5, 'class_weight': 'balanced'}

In [85]:
y_train_pred = best_model.predict(x_train)
y_test_pred = best_model.predict(x_test)

In [86]:
print("Training Metrics")
print("Accuracy :", accuracy_score(y_train, y_train_pred))
print("Precision:", precision_score(y_train, y_train_pred))
print("Recall   :", recall_score(y_train, y_train_pred))
print("F1 Score :", f1_score(y_train, y_train_pred))
print("ROC-AUC  :", roc_auc_score(y_train, y_train_pred))
print("\n")

print("Testing Metrics")
print("Accuracy :", accuracy_score(y_test, y_test_pred))
print("Precision:", precision_score(y_test, y_test_pred))
print("Recall   :", recall_score(y_test, y_test_pred))
print("F1 Score :", f1_score(y_test, y_test_pred))
print("ROC-AUC  :", roc_auc_score(y_test, y_test_pred))

Training Metrics
Accuracy : 0.7566222222222222
Precision: 0.5272491349480969
Recall   : 0.8153846153846154
F1 Score : 0.6403992645127397
ROC-AUC  : 0.7753678524864964


Testing Metrics
Accuracy : 0.728500355366027
Precision: 0.4933993399339934
Recall   : 0.7994652406417112
F1 Score : 0.610204081632653
ROC-AUC  : 0.7511362989268575

In [87]:
!pip install pickle

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)
ERROR: No matching distribution found for pickle

In [88]:
import pickle
pickle.dump(best_model,open("model.pkl","wb"))
pickle.dump(preprocessor,open("preprocessor.pkl","wb"))